version: "3"

networks:
  app:
    driver: "bridge"

services:
###############################################
 selenium-hub:
  image: selenium/hub
  container_name: selenium-hub
  ports:
   - "4442:4442"
   - "4443:4443"
   - "4444:4444"
  networks:
   - app

###############################################
 chrome:
  image: selenium/node-chrome
  depends_on:
   - selenium-hub
  networks:
   - app
  environment:
   - SE_EVENT_BUS_HOST=selenium-hub
   - SE_EVENT_BUS_PUBLISH_PORT=4442
   - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   - HUB_PORT_4444_TCP_ADDR=selenium-hub
   - HUB_PORT_4444_TCP_PORT=4444
   - SE_NODE_MAX_SESSIONS=3
   - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#  ports:
#   - "5901:5900"

###############################################
  # nodejs:
    #  container_name: selenium-nodejs
    #build:
#context: ./services/nodejs
#   dockerfile: Dockerfile
    #  volumes:
      #   - ./services/nodejs/src:/home/app
      #   - /home/app/node_modules
    #  environment:
      #   - HUB_PORT_4444_TCP_ADDR=selenium-hub
      #   - HUB_PORT_4444_TCP_PORT=4444
    #  networks:
      #   - app

### Pyapp ###########################################
 pyapp:
  container_name: selenium-python
  build:
    context: ./services/app
    args:
      - PYTHON_VERSION=${PYTHON_VERSION}
  command: python manage.py run -h 0.0.0.0
  volumes:
    - ./services/app/:/usr/src/app/
  ports:
    - "${FLASK_PORT}:5000"
  restart: always
  environment:
    - FLASK_APP=${FLASK_APP}
    - FLASK_ENV=${FLASK_ENV}
    - APP_FOLDER=${APP_FOLDER}
    - TZ=Asia/Ho_Chi_Minh
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
  networks:
    - app

